#ifndef TUCSENCONST_H
#define TUCSENCONST_H

static char m_strArrProp[][128] = { 
"TUIDP_GLOBALGAIN      : [Global Gain]                ",
"TUIDP_EXPOSURETM      : [Exposure Time]              ",
"TUIDP_BRIGHTNESS      : [Brightness(Auto Exposure)]  ",
"TUIDP_BLACKLEVEL      : [Black Level]                ",
"TUIDP_TEMPERATURE     : [Temperature]                ",
"TUIDP_SHARPNESS       : [Sharpness]                  ",
"TUIDP_NOISELEVEL      : [Noise Level]                ",
"TUIDP_HDR_KVALUE      : [HDR K Value]                ",
"TUIDP_GAMMA           : [Gamma]                      ",
"TUIDP_CONTRAST        : [Contrast]                   ",
"TUIDP_LFTLEVELS       : [Left Levels]                ",
"TUIDP_RGTLEVELS       : [Right Levels]               ",
"TUIDP_CHNLGAIN        : [Channel Gain]               ",
"TUIDP_SATURATION      : [Saturation]                 ",
"TUIDP_CLRTEMPERATURE  : [Color Temperature]          ",
"TUIDP_CLRMATRIX       : [Color Matrix]               ",
"TUIDP_DPCLEVEL        : [DPC Level]                  ",
"TUIDP_BLACKLEVELHG    : [Black Level High Gain]      ",
"TUIDP_BLACKLEVELLG    : [Black Level Low Gain]       ",
"TUIDP_POWEEFREQUENCY  : [Power frequency]            ",
"TUIDP_HUE             : [Hue]                        ",
"TUIDP_LIGHT           : [Light]                      ",
"TUIDP_ENHANCE_STRENGTH: [Enhance strength]           ",
"TUIDP_NOISELEVEL_3D   : [Noise Level 3D]             ",
"TUIDP_FOCUS_POSITION  : [Position]                   ",
"TUIDP_FRAME_RATE      : [Frame Rate]                 ",
"TUIDP_START_TIME      : [Start Time]                 ",
"TUIDP_FRAME_NUMBER    : [Frame Number]               ",
"TUIDP_INTERVAL_TIME   : [Interval Time]              ",
"TUIDP_GPS_APPLY       : [GPS Apply]                  ",
"TUIDP_AMB_TEMPERATURE : [Amb Temperature]            ",
"TUIDP_AMB_HUMIDITY    : [Amb Humidity]               ",
"TUIDP_AUTO_CTRLTEMP   : [Auto Control Temperature]   ",
"TUIDP_AVERAGEGRAY     : [Average]                    ",
"TUIDP_AVERAGEGRAYTHD  : [Average Gray Thd]           ",
"TUIDP_ENHANCETHD      : [Enhance Threshold ]         ",
"TUIDP_ENHANCEPARA     : [Enhance Parameter]          ",
"TUIDP_EXPOSUREMAX     : [Exposure Max]               ",
"TUIDP_EXPOSUREMIN     : [Exposure Min]               ",
"TUIDP_GAINMAX         : [Gain Max]                   ",
"TUIDP_GAINMIN         : [Gain Min]                   ",
"TUIDP_THROUGHFOGPARA  : [Through Fog]                ",
"TUIDP_ATLEVEL_PERCENTAGE   : [Auto Level Ignore]     ",
"TUIDP_TEMPERATURE_TARGET   : [Temperature Target]    ",
"TUIDP_PIXELRATIO      : [pixel ratio]                ",
};

#endif