/* ********************************************************************
    Plugin "AerotechA3200" for itom software
    URL: http://www.uni-stuttgart.de/ito
    Copyright (C) 2018, Institut fuer Technische Optik (ITO),
    Universitaet Stuttgart, Germany

    This file is part of a plugin for the measurement software itom.

    This itom-plugin is free software; you can redistribute it and/or modify it
    under the terms of the GNU Library General Public Licence as published by
    the Free Software Foundation; either version 2 of the Licence, or (at
    your option) any later version.

    itom and its plugins are distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Library
    General Public Licence for more details.

    You should have received a copy of the GNU Library General Public License
    along with itom. If not, see <http://www.gnu.org/licenses/>.
*********************************************************************** */

/**\file dialogAerotechA3200.h
* \brief In this file the class of the modal dialog for the AerotechA3200 are specified
*
*\sa dialogAerotechA3200, AerotechA3200
*\author Wolfram Lyda
*\date    Oct2011
*/

#include "common/sharedStructures.h"
#include "common/sharedStructuresQt.h"
#include "common/addInInterface.h"

#include "ui_dialogAerotechA3200.h"    //! Header-file generated by Qt-Gui-Editor which has to be called

#include <qdialog.h>

//----------------------------------------------------------------------------------------------------------------------------------
/** @class dialogAerotechA3200
*   @brief Config dialog functionality of AerotechA3200
*
*   This class is used for the modal configuration dialog. It is used for parameter setup and calibration.
*    ui_dialogAerotechA3200.h is generated by the Gui-Editor.
*
*\sa AerotechA3200
*/
class dialogAerotechA3200 : public QDialog
{
    Q_OBJECT

    private:
        Ui::dialogAerotechA3200 ui;    //! Handle to the dialog
        ito::AddInActuator *m_pAerotechA3200;    //! Handle to the attached motor to invoke calib command
        int m_numaxis;    //!    Number of axis of this device
        QVector<QDoubleSpinBox*> m_pDialogSpeed;
        QVector<QLabel*> m_pDialogSpeedLabel;
        QVector<QCheckBox*> m_pDialogEnabled;

    public:
        dialogAerotechA3200(ito::AddInActuator *motor, QStringList axisNames);
        ~dialogAerotechA3200() {};
        int setVals(QMap<QString, ito::Param> *paramVals); //!< Function called by AerotechA3200::showConfDialog to set parameters values at dialog startup
        int getVals(QMap<QString, ito::Param> *paramVals);    //!< Function called by AerotechA3200::showConfDialog to get back the changed parameters

    public slots:

    private slots:
        void on_pushButtonCalib_clicked();    //!< If the Botton invokes a AerotechA3200::Calib of enabled Axis
};
